# Generated by Django 5.1 on 2024-08-29 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Savoir-faire')),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Intitulé du poste')),
                ('experience', models.IntegerField(blank=True, null=True, verbose_name='Expérience souhaitée')),
            ],
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Savoir-être')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse mail')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom')),
                ('experience', models.IntegerField(default=0, verbose_name='Années expérience')),
            ],
        ),
        migrations.CreateModel(
            name='JobHardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, verbose_name='Niveau de compétence souhaité')),
                ('hardskill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.hardskill', verbose_name='Hard skills souhaité')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_hardskills', to='matching.joboffer')),
            ],
        ),
        migrations.CreateModel(
            name='JobSoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, verbose_name='Niveau de compétence souhaité')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_softskills', to='matching.joboffer')),
                ('softskill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.softskill', verbose_name='Soft skill souhaité')),
            ],
        ),
        migrations.CreateModel(
            name='UserHardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, verbose_name='Note / niveau')),
                ('hardskill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matching.hardskill', verbose_name='Hard skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.user', verbose_name='Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='UserSoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, verbose_name='Note / niveau')),
                ('softskill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.softskill', verbose_name='Soft skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.user', verbose_name='Utilisateur')),
            ],
        ),
    ]
