name: Deploy Job matching

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  Deploy:
    name: Deploy Job matching
    runs-on: ubuntu-latest

    steps:
      - name: Checkout file
        uses: actions/checkout@v4
      
      # run test
      -name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

       - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.USER_NAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/job-matching